// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  firebaseConfig: {
    apiKey: 'AIzaSyDl6Y7dFs6u0M5zBW5vHH2GZDir27GeA_E',
    authDomain: 'prueba-tecnica-5de87.firebaseapp.com',
    projectId: 'prueba-tecnica-5de87',
    storageBucket: 'prueba-tecnica-5de87.appspot.com',
    messagingSenderId: '290444050447',
    appId: '1:290444050447:web:e100f887c3b7342f0ea37a',
  },
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
};
